### ISSUE TITLE
Address in GUI wallet is not shown completly. Last char hidden

### ISSUE THREAD

**Issue by TLausZ** [turtlecoin/turtle-wallet-xamarin#32]
I think this is bad UI/UX. choose a smaller font.
![lastchar-hidden](https://user-images.githubusercontent.com/9079817/37224330-687bd4ca-23d3-11e8-9ad7-bd891c220737.gif)

**Comment by jerme404** [comment]
The entire window has been resized to accommodate the full address, it'll be in the next release.

<img width="714" alt="screen shot 2018-04-06 at 8 46 29 pm" src="https://user-images.githubusercontent.com/29779465/38449414-c136efc2-39dc-11e8-8e59-97d035f7cbf6.png">
