### ISSUE TITLE
Transactions decimals shown as .00, even though it isn't.

### ISSUE THREAD

**Issue by Swardu** [turtlecoin/turtle-wallet-xamarin#36]
This only happens for transactions, balance works fine.

CLI: 
![image](https://user-images.githubusercontent.com/27481108/37681532-4413aca4-2c87-11e8-9c1e-b3877aa5153f.png)

GUI: 
![image](https://user-images.githubusercontent.com/27481108/37681523-3cb65286-2c87-11e8-922f-f3ae034a502d.png)

**Comment by hensleyrob** [comment]
This should be fixed in master and included in the next release. #28

**Comment by jerme404** [comment]
I confirmed this is fixed in the latest release.

https://github.com/turtlecoin/turtle-wallet-xamarin/releases/tag/1.0.6666.17114

<img width="660" alt="screen shot 2018-04-06 at 8 24 22 pm" src="https://user-images.githubusercontent.com/29779465/38449068-8f526508-39d8-11e8-9224-d7fab135ad13.png">
